# Copyright (c) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2016-present Sven Greb <code@svengreb.de>

# Project:    Nord
# Repository: https://github.com/arcticicestudio/nord
# License:    MIT
# References:
#   https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
dist: trusty
sudo: false
node_js:
  - "node"
os:
  - linux
  - osx
before_install:
  - rm -rf ./node_modules
before_script:
  - npm install
script:
  - npm run test
  - npm run docs:build
  - npm run sassdoc
  - npm run dist
